version: '2'



services:



 swagger_website:
    build: .
    image: ohdsi/usagi_swagger_website:1.0.0
    container_name: broadsea-usagi-swagger-website
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"